### ISSUE TITLE
Durin icon not showing up correctly on android

### ISSUE THREAD

**Issue by meandavejustice** [ipfs-shipyard/Durin#20]
![Screenshot_20230309-190549_2](https://user-images.githubusercontent.com/1844554/224126279-be7de2f7-2ae6-4151-a3be-e036bb5bf217.png)

Installed from google play store, tested on Pixel 6 and Fairphone 4

**Comment by yocontra** [comment]
@meandavejustice Is this still an issue? Maybe something @drewdelano can look into

**Comment by meandavejustice** [comment]
No this was fixed
