### ISSUE TITLE
Berty's OrbitDB + Bluetooth

### ISSUE THREAD

**Issue by TheRook** [ipfs-shipyard/Durin#4]
Berty uses IPFS and wrote their own magic Bluetooth sync layer for mobile:
https://berty.tech/blog/bluetooth-low-energy/
https://www.youtube.com/watch?v=cC-tXnMyiBc&t=1s

They are open source on github and have both an iOS and Android implementation, reach out to Berty and tell them about Durin's file sharing over bluetooth and hopefully you both can use a common protocol that works between both of your apps and any other app that wants file sharing on IPFS.

**Comment by meandavejustice** [comment]
Hey @TheRook thanks for reaching out. We are aware of Berty's awesome work on mobile. We will definitely be in touch with them

**Comment by TheRook** [comment]
Dope project btw.  I would be more upfront about the fact that government can just ask Apple to shutdown file sharing and that isn't cool.   I wish the public announcement was a bit more political given the current news.
